name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # uruchamia się codziennie o północy
  workflow_dispatch:      # możliwość ręcznego uruchomienia

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake SVG
        uses: Platane/snk@master
        with:
          github_user_name: marcinwitnik
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
